/**
 * Nepal Survey Coordinates to Google Earth KML Converter
 * Supports:
 * - WGS84 Lat/Long (decimal degrees)
 * - Nepal MUTM (Modified Universal Transverse Mercator, Everest 1830 / WGS84)
 *   Central Meridians: 81°E (West Nepal), 84°E (Central Nepal), 87°E (East Nepal)
 */

export interface SurveyPoint {
  id: string;
  name: string;
  x: number; // Easting or Longitude
  y: number; // Northing or Latitude
  z?: number; // Elevation
  description?: string;
}

// Convert MUTM Easting/Northing to approximate WGS84 Lat/Long for Nepal
export function mutmToLatLong(easting: number, northing: number, cm: 81 | 84 | 87 = 84): { lat: number; lon: number } {
  // If coordinates are already in Lat/Long range (Nepal Lat: 26-31, Lon: 80-89)
  if (northing >= 25 && northing <= 32 && easting >= 79 && easting <= 90) {
    return { lat: northing, lon: easting };
  }

  // Standard UTM / MUTM Inverse projection parameters
  // False Easting = 500,000m, Scale Factor k0 = 0.9999 for Nepal MUTM (or 0.9996 for UTM)
  const a = 6378137.0; // WGS84 major axis
  const f = 1 / 298.257223563;
  const e2 = 2 * f - f * f;
  const e1 = (1 - Math.sqrt(1 - e2)) / (1 + Math.sqrt(1 - e2));

  const k0 = 0.9999;
  const falseEasting = 500000.0;
  const x = easting - falseEasting;
  const y = northing;

  const m = y / k0;
  const mu = m / (a * (1 - e2 / 4 - 3 * e2 * e2 / 64 - 5 * Math.pow(e2, 3) / 256));

  const phi1Rad = mu +
    (3 * e1 / 2 - 27 * Math.pow(e1, 3) / 32) * Math.sin(2 * mu) +
    (21 * e1 * e1 / 16 - 55 * Math.pow(e1, 4) / 32) * Math.sin(4 * mu) +
    (151 * Math.pow(e1, 3) / 96) * Math.sin(6 * mu);

  const n1 = a / Math.sqrt(1 - e2 * Math.sin(phi1Rad) * Math.sin(phi1Rad));
  const t1 = Math.tan(phi1Rad) * Math.tan(phi1Rad);
  const c1 = (e2 / (1 - e2)) * Math.cos(phi1Rad) * Math.cos(phi1Rad);
  const r1 = a * (1 - e2) / Math.pow(1 - e2 * Math.sin(phi1Rad) * Math.sin(phi1Rad), 1.5);
  const d = x / (n1 * k0);

  const latRad = phi1Rad - (n1 * Math.tan(phi1Rad) / r1) * (
    d * d / 2 -
    (5 + 3 * t1 + 10 * c1 - 4 * c1 * c1 - 9 * (e2 / (1 - e2))) * Math.pow(d, 4) / 24 +
    (61 + 90 * t1 + 298 * c1 + 45 * t1 * t1 - 252 * (e2 / (1 - e2)) - 3 * c1 * c1) * Math.pow(d, 6) / 720
  );

  const lonRad = (d - (1 + 2 * t1 + c1) * Math.pow(d, 3) / 6 +
    (5 - 2 * c1 + 28 * t1 - 3 * c1 * c1 + 8 * (e2 / (1 - e2)) + 24 * t1 * t1) * Math.pow(d, 5) / 120) / Math.cos(phi1Rad);

  const lat = (latRad * 180) / Math.PI;
  const lon = cm + (lonRad * 180) / Math.PI;

  return { lat, lon };
}

export function generateKml(
  points: SurveyPoint[],
  layerName: string = 'Nepal Survey Points',
  connectLine: boolean = false,
  cm: 81 | 84 | 87 = 84
): string {
  const converted = points.map((p) => {
    const coords = mutmToLatLong(p.x, p.y, cm);
    return {
      ...p,
      lat: coords.lat,
      lon: coords.lon,
    };
  });

  let placemarksXml = '';
  let lineCoordinates: string[] = [];

  for (const pt of converted) {
    const elevation = pt.z !== undefined ? pt.z : 0;
    lineCoordinates.push(`${pt.lon},${pt.lat},${elevation}`);

    placemarksXml += `
    <Placemark>
      <name>${pt.name}</name>
      <description><![CDATA[
        <b>Point:</b> ${pt.name}<br/>
        <b>Easting (X):</b> ${pt.x}<br/>
        <b>Northing (Y):</b> ${pt.y}<br/>
        <b>Elevation (Z):</b> ${elevation}m<br/>
        <b>Code:</b> ${pt.description || 'Survey Point'}
      ]]></description>
      <Point>
        <coordinates>${pt.lon},${pt.lat},${elevation}</coordinates>
      </Point>
    </Placemark>`;
  }

  let lineStringXml = '';
  if (connectLine && lineCoordinates.length > 1) {
    lineStringXml = `
    <Placemark>
      <name>Boundary / Survey Path</name>
      <Style>
        <LineStyle>
          <color>ff0000ff</color>
          <width>3</width>
        </LineStyle>
      </Style>
      <LineString>
        <extrude>1</extrude>
        <tessellate>1</tessellate>
        <coordinates>
          ${lineCoordinates.join(' ')}
        </coordinates>
      </LineString>
    </Placemark>`;
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${layerName}</name>
    <description>Generated by BR Bhatta Survey Portal (brbhatta.com)</description>
    ${placemarksXml}
    ${lineStringXml}
  </Document>
</kml>`;
}
